### ISSUE TITLE
Getting error: /usr/local/bin/phpstan: line 2: syntax error: unexpected newline

### ISSUE THREAD

**Issue by bshaffer** [php-actions/phpstan#10]
When I use this action to run `phpstan` in my github actions, I get the following error:
```
/usr/local/bin/phpstan: line 2: syntax error: unexpected newline
```

Looking at the debug output, this is from the following command (which run locally, executes as expected):

```
  Command:  phpstan analyse appengine/flexible/tasks/src --autoload-file=appengine/flexible/tasks/vendor/autoload.php
```

You can see [the full run log here](https://github.com/GoogleCloudPlatform/php-docs-samples/runs/4437822608?check_suite_focus=true)

I have also tried setting the PHP version to 7.4 for both the composer action and the phpstan action, with no luck.

Any thoughts?

```yaml
name: Lint

on: [push]

jobs:
  phpstan:
    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6 # or alternative dependency management
      with:
        args: --working-dir=logging --ignore-platform-reqs

    - uses: php-actions/phpstan@v3
      with:
        php_version: "8.0"
        path: logging/src
        autoload_file: logging/vendor/autoload.php
```

**Comment by g105b** [comment]
Hi @bshaffer ,

Thanks for raising this issue. I'll take a look into it for you later. In the meantime, would you be able to compare to https://github.com/php-actions/example-phpstan as a known working project?

Thanks,
Greg.

**Comment by bshaffer** [comment]
I ended up calling the binary directly instead of using this action

https://github.com/GoogleCloudPlatform/php-docs-samples/pull/1569

**Comment by g105b** [comment]
Interesting. It would still be useful to use this action, so you can get your builds a lot quicker than 2 minutes. For debugging's sake, would you be able to delete the packages created on the repo here: https://github.com/orgs/GoogleCloudPlatform/packages?repo_name=php-docs-samples and then try again? I'm wondering whether there was a build error and something fishy has been cached.

**Comment by bshaffer** [comment]
@g105b done. Why would this be generating packages though?

**Comment by g105b** [comment]
It builds the PHP environment and PhpStan project, and caches the packages on the repository to achieve builds that only take a few seconds to execute. At the time of ghcr.io being a new deal, this was the only way to do it (storing packages on the repository, rather than within php-actions organisation). I'm open to other ways of working.

Did the removal fix the issue for you?

**Comment by bshaffer** [comment]
Because the repo I'm in has to run in multiple subdirectories (we have ~30 sample directories, each with their own `composer,json`), I do not think the action will work for me. 

Previously I was splitting it out into 30 separate jobs, but this was more trouble than it's worth (the job was generating 30 individual checks that diluted the more important unit test checks). I do not believe it's current form (looping through all relevant directories and running `composer install` and `phpstan` in each of them) is supported by this action. 

If I'm wrong and this use-case _is_ supported, please let me know!

**Comment by g105b** [comment]
Thank you for the update, Brent. This is certainly something I will pay some attention to, as I'd like this action to be as accessible as possible to everyone. Running an individually-installed `phpstan` on each of the sample directories is indeed a workflow that isn't supported by this action, but maybe there are alternative approaches you could take? For instance, maybe something like this:

```
    - name: PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: example/dir1 example/dir2 example/dir3 ...etc.
```

I understand that this might not satisfy your particular use case, but I thought it was worth sharing.

I'll close this issue now but feel free to continue the discussion - always happy to help.

**Comment by MarcinOrlowski** [comment]
Let me just add $0.03 here and point out that proposed `path` arguments format:
```yaml
    - name: PHPStan
      uses: php-actions/phpstan@v3
      with:
        path: example/dir1 example/dir2 example/dir3 ...etc.
```

is counter intuitive, as in yaml you should do normal list instead

```yaml
        path: 
            - example/dir1
            - example/dir2
            - example/dir3 
            - ...etc.
```
