### ISSUE TITLE
`paths-file` option does not exist

### ISSUE THREAD

**Issue by myyk** [php-actions/phpstan#16]
The "--paths-file" option does not exist, though there's mention of it in https://github.com/php-actions/phpstan#inputs.

I tried to use it like this:

```
      - name: PHPStan Static Analysis
        uses: php-actions/phpstan@v3
        with:
          memory_limit: 1G
          paths_file: .phpstan.paths
```

When running it the action I saw this error:

```
  The "--paths-file" option does not exist.  
```

Seems like this isn't implemented anymore?
