### ISSUE TITLE
Adding multiple paths does not work

### ISSUE THREAD

**Issue by jgrygierek** [php-actions/phpstan#17]
I have such config:

```yaml
-   name: Run PHPStan
    uses: php-actions/phpstan@v3
    with:
        path: src tests
```

And I get: `Path /app/src tests does not exist`
