### ISSUE TITLE
Odd difference to local phpstan

### ISSUE THREAD

**Issue by wlfio** [php-actions/phpstan#3]
Locally I am using phpstan's docker one liner
```
$ docker run --rm -v /home/wlfio/work/<redacted>:/app phpstan/phpstan --no-interaction --no-progress analyse --error-format=github
Note: Using configuration file /app/phpstan.neon.

 [OK] No errors
```
And getting the above result

using this workflow step
```
      - name: PHPStan Analysis
        uses: php-actions/phpstan@v1
        with:
          error_format: github
```

I am getting

```
Command: phpstan --no-interaction --no-progress analyse --error-format=github
Note: Using configuration file /github/workspace/phpstan.neon.
 ------ -------------------------------------------------------------------- 
  Line   src/Config.php                                                      
 ------ -------------------------------------------------------------------- 
  46     Constant APP_ROOT not found.                                        
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
  49     Constant APP_ROOT not found.                                        
         💡 Learn more at https://phpstan.org/user-guide/discovering-symbols  
 ------ -------------------------------------------------------------------- 
```

This is the neon file
```
parameters:
    level: 3
    paths:
        - src/
```
