### ISSUE TITLE
How to report issues on changed files/lines only?

### ISSUE THREAD

**Issue by rlorenzo** [php-actions/phpstan#5]
I am using this action on a legacy project and it is producing a lot of noise because it 1864 errors. But is it possible to make this action only inspect the files/lines that were changed in the given commit/pull request only?

**Comment by g105b** [comment]
Hi @rlorenzo,

Yes sure, you can configure what you wish to test by adding a configuration file or via the `paths` input.

Your config file can be specified like this:

```
- name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        configuration: your-config.neon
```

Or you can specify a list of paths like this:

```
- name: PHPStan Static Analysis
      uses: php-actions/phpstan@v2
      with:
        path: src/new/foldere src/another-new/folder
```

I hope this helps!
